<?php
// Plugin definition
$plugin = array(
  'title' => t('Layout One Column'),
  'icon' => 'one_col.png',
  'category' => t('Bookingcar Layouts'),
  'theme' => 'one_col',
  'regions' => array(
    'feature' => t('Feature'),
    'contentmain_top' => t('Content Top'),
    'contentmain_top_full' => t('Content top Full'),
    'contentmain_full' => t('Content Full'),
    'contentmain' => t('Content'),
  ),
);
